# Generated by Django 5.2.15 on 2026-06-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('max_booking_days_ahead', models.PositiveIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='resource_capacity_gte_1'), models.CheckConstraint(condition=models.Q(('max_booking_days_ahead__gte', 1)), name='resource_max_booking_days_ahead_gte_1')],
            },
        ),
    ]
