# Generated by Django 5.2.15 on 2026-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='cancellation_deadline_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='resource',
            name='max_booking_duration_minutes',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='resource',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('max_booking_duration_minutes__gte', 1)), name='resource_max_duration_minutes_gte_1'),
        ),
    ]
